### ISSUE TITLE
Add g shortcuts

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/coreutils-feedstock#5]
It's useful for coreutils to have g shortcuts, like `gsort`, and so on, so that scripts can ensure that they are using the coreutils versions of a command.

**Comment by sodre** [comment]
would you have time to contribute a pr?

**Comment by asmeurer** [comment]
Actually what would be more useful to me would be if there were a separate package that used only g-prefixed commands. coreutils replacing common commands like `ls` on my Mac with GNU versions tends to break stuff.

**Comment by ngam** [comment]
@asmeurer how about a separate output (call it gnu-coreutils) where all are prefixed with g? `./configure --prefix=$PREFIX --program-prefix=g`
